".vimrc file - Save this file as .vimrc in your home directory. (e.g. /home/user/.vimrc)

"Generated by vimrcgenerator.appspot.com
"Author: Robert Pyke


"-- General --
set number		"Show line numbers
set ruler		"Show the line and column number of the cursor position

"-- Programming --
set autoindent		"Copy indent from current line when starting a new line

"-- Spaces/Tabs --
set noexpandtab		"Strictly use tabs when tab is pressed (this is the default)
set shiftwidth=4
set tabstop=4

"-- Searching --
set hlsearch		"Highlight search results
set ignorecase		"When doing a search, ignore the case of letters
set smartcase		"Override the ignorecase option if the search pattern contains upper case letters
"Clear the search highlight by pressing ENTER when in Normal mode (Typing commands)
:nnoremap <CR> :nohlsearch<CR>/<BS><CR>

"-- Tabbed Editing --
"Open a new (empty) tab by pressing CTRL-T. Prompts for name of file to edit
map <C-T> :tabnew<CR>:edit 
"Open a file in a new tab by pressing CTRL-O. Prompts for name of file to edit
map <C-O> :tabfind 
"Switch between tabs by pressing Shift-Tab
map <S-Tab> gt

"-- Tweaks --
"Add tweak for better backspace support
set backspace=indent,eol,start

" Turn on syntax highlighting!
syntax on

"----------------------
"-- Personal changes --
"----------------------

"Start pathogen
call pathogen#infect()

"Select theme
:color jellybeans

"NERDTree toggle shortcut
noremap <C-F> :NERDTreeToggle<CR>
vnoremap <C-F> <C-C>:NERDTreeToggle<CR>
inoremap <C-F> <C-O>:NERDTreeToggle<CR>

"Fix minibuf/nerdtree issue
let g:miniBufExplModSelTarget = 1

"Buffer switching shortcuts
" Previous tab (Ctrl-H or Ctrl-J)
noremap <C-J> :bp<CR>
noremap <C-H> :bp<CR>
vnoremap <C-J> <C-C>:bp<CR>
vnoremap <C-H> <C-C>:bp<CR>
inoremap <C-J> <C-O>:bp<CR>
inoremap <C-H> <C-O>:bp<CR>

" Next tab
noremap <C-K> :bn<CR>
noremap <C-L> :bn<CR>
vnoremap <C-K> <C-C>:bn<CR>
vnoremap <C-L> <C-C>:bn<CR>
inoremap <C-K> <C-O>:bn<CR>
inoremap <C-L> <C-O>:bn<CR>

